Add new patch file for aim ui
G-Research/fasttrackml pull request #133
Opened 2023-06-23 15:47 UTC by galadd

This is a draft PR for #92  made for a new file custom2.patch. I want to know i this is how it is going to look before I append it to custom.patch

Expectation: Aim uses fasttrack tracking server on the Aim UI Quickstart screen

2023-06-23 15:57 UTC, suprjinx commented on pkg/ui/aim/embed/custom2.patch
> ++  const { hostname, port } = window.location;
great solution!

2023-06-26 21:49 UTC, suprjinx commented
@jgiannuzzi This looks great in the AIM ui, here's a pic below. I have question -- should the framework-specific help sections (the accordian of frameworks) receive any change of instructions? It seems like they are not referencing the tracking server, just local logging.

![image](https://github.com/G-Research/fasttrackml/assets/1463452/9949fadb-9427-4992-b627-183d4a4c7d5d)

2023-06-27 00:11 UTC, galadd commented
I have observed in the shared screenshot that I overlooked an important detail: I forgot to convert the server into a string. However, I have rectified this issue in the latest commit.

2023-06-27 15:17 UTC, suprjinx submitted a review, later dismissed

2023-06-30 13:38 UTC, jgiannuzzi requested changes
Thanks a lot for your PR @galadd! 🙏

I like how you're getting the tracking server information from the browser!

However, the instructions need to be changed to use MLFlow instead of Aim, as we do not support logging metrics with the Aim SDK (and we won't in the future either). Could you please adapt them with a simple equivalent script using MLFlow?

With regards to the accordion, we should adapt all of these examples to use MLFlow and our tracking server where possible. For the frameworks that would not be supported, we should simply remove them.

2023-07-03 19:51 UTC, suprjinx commented on pkg/ui/aim/embed/custom.patch
> ++mlflow.set_tracking_uri("${fasttrack_server}")
definitely correct now -- using the mlflow client :-)

2023-07-04 09:37 UTC, jgiannuzzi commented
Superseded by #149

2023-07-04 09:37 UTC, closed without merging