Artifacts list error
G-Research/fasttrackml pull request #348
Opened 2023-09-19 14:06 UTC by suprjinx

Fixes #307

2023-09-19 21:53 UTC, suprjinx commented
working for local storage now: 
![image](https://github.com/G-Research/fasttrackml/assets/1463452/41613850-f130-40f5-b6cc-45f4d7049545)

2023-09-20 16:24 UTC, jgiannuzzi requested changes

2023-09-20 16:24 UTC, jgiannuzzi commented on pkg/api/mlflow/service/artifact/storage/local.go
> +			Path:  info.Name(),
this is incorrect, the path should be `path` parameter + the file name

2023-09-20 16:44 UTC, suprjinx commented on pkg/api/mlflow/service/artifact/storage/local.go
> +		return path, []ArtifactObject{}, nil
wil do

2023-09-20 16:44 UTC, suprjinx commented on pkg/api/mlflow/service/artifact/storage/local.go
> +		log.Infof("artifact dir does not exist: %s", path)
will do

2023-09-20 16:53 UTC, suprjinx commented on pkg/api/mlflow/service/artifact/storage/local.go
> +	return path, artifactList, nil
i'm confused, then, because it seems like it wants "artifact root" + "run path" to equal the directory containing the list?

2023-09-20 16:55 UTC, suprjinx commented on pkg/api/mlflow/service/artifact/storage/local.go
> +func (s Local) List(runArtifactPath, additionalPath string) (string, []ArtifactObject, error) {
it seems like a "path" in this case, no "file://" scheme

2023-09-20 17:35 UTC, closed without merging

2023-09-20 17:35 UTC, jgiannuzzi commented
superseded by #367