Helm chart - fasttrackml
G-Research/fasttrackml pull request #845
Opened 2024-01-31 14:36 UTC by ljubon

The goal of this PR is to package FastTrackML and allow contributors to also use it inside a Kubernetes cluster with simple installation
The scope of change includes

- [x] using existing Docker Image as a base image for k8s deployment
  - [x] migrating [.env](https://github.com/ljubon/fasttrackml/blob/main/.devcontainer/.env) file to [ConfigMap](https://github.com/ljubon/fasttrackml/blob/3bfd8bb82d37dce56ec3f8ac95bfea76a99c16e5/helm/fasttrackml/values.yaml#L14) with exposing `data` section in default [values.yaml](https://github.com/ljubon/fasttrackml/blob/3bfd8bb82d37dce56ec3f8ac95bfea76a99c16e5/helm/fasttrackml/values.yaml#L14) file
- [x] publishing the helm chart to main G-Research/charts with the rest of the charts
  - [x] __NOTE__: For this action org owner will need to create secrets and follow process to onboard `fasttrackml` to this publishing  mehanism
  - [x] PR for adding `fastrackml` charts to the G-Research/config https://github.com/G-Research/charts/pull/130

#### Testing helm chart

```bash
git checkout oss-350-helm-chart-lvl-2
kind create cluster --name fastrackml
kubectl cluster-info --context kind-fastrackml
helm install fasttrackml ./helm/fasttrackml
kubectl port-forward deployment/fasttrackml 5000:5000

# Cleanup command
kind delete cluster --name fastrackml
```

In your local browser at http://localhost:5000 service will be exposed

Resolves: https://github.com/G-Research/oss-portfolio-maturity/issues/350

2024-02-13 16:08 UTC, suprjinx commented on helm/fasttrackml/values.yaml
> +  FML_DEV_MODE: true
We should add `FML_DATABASE_URI` as an environment var -- with examples for sqlite and postgres

2024-02-13 16:11 UTC, suprjinx commented on helm/fasttrackml/values.yaml
> +  POSTGRES_USER: postgres
POSTGRES settings are not really part of this service. We put user/pwd/host/db in the FML_DATABASE_URI for postgres.

2024-02-13 16:43 UTC, suprjinx commented
I get an error installing the chart: ```gwilson@macbook ~/P/fasttrackml (pr/845)> helm install fasttrackml ./helm/fasttrackml
Error: INSTALLATION FAILED: ConfigMap in version "v1" cannot be handled as a ConfigMap: json: cannot unmarshal bool into Go struct field ConfigMap.data of type string```

2024-02-19 15:41 UTC, suprjinx commented on helm/fasttrackml/values.yaml
> +sqlite:
I don't think this sqlite.enabled switch is really needed -- in the app, sqlite is enabled by using a sqlite uri in the FML_DATABASE_URI field. Maybe you could just put a commented-out sqlite uri example next to the postgres URI, which points to a file on the volume mount?

2024-02-19 15:42 UTC, suprjinx commented on helm/fasttrackml/values.yaml
> +sqlite:
(that is, points to a file on this commented-out volume mount)

2024-02-19 17:53 UTC, suprjinx commented
> > I get an error installing the chart: `gwilson@macbook ~/P/fasttrackml (pr/845)> helm install fasttrackml ./helm/fasttrackml Error: INSTALLATION FAILED: ConfigMap in version "v1" cannot be handled as a ConfigMap: json: cannot unmarshal bool into Go struct field ConfigMap.data of type string`
> 
> Hi @suprjinx, thank you for your time and review 🙏 The above comments are resolved, let me know if the new changes are as you requested
> 
> Regarding the error you encountered, it was specific to templating boolean values of `FML_DEV_MODE`. The fix is in the latest commit with an additional note to keep in mind to quote all values passed under the `data:` section in `values.yaml`

Thank you @ljubon for the contribution! I had one more suggestion on how to simplify the values.yaml

2024-02-23 01:29 UTC, suprjinx commented on helm/fasttrackml/values.yaml
> +  # FML_DATABASE_URI: "/data/mydatabase.db # SQLite
this would take uri of `"sqlite:///data/mydatabase.db"`

2024-02-27 15:35 UTC, suprjinx approved these changes
This looks great, thanks for making those changes! Do you think we need to add ingress? (can be new ticket)

2024-02-28 14:37 UTC, suprjinx approved these changes

2024-04-25 07:48 UTC, jgiannuzzi commented
@ljubon Secrets created under the `release` environment. The key fingerprint to add to [`config.json`](https://github.com/G-Research/charts/blob/master/.github/workflows/scripts/config.json) is `Da10MkM0RnFLWCcBbZ8ij+lYntgMDGSBdhljq+Oz5HY=`.

2024-04-25 07:50 UTC, jgiannuzzi requested changes

2024-04-25 07:50 UTC, jgiannuzzi commented on .github/workflows/release.yml
> +    if: startsWith(github.ref, 'refs/tags/v') || github.ref == 'refs/heads/main'
we only want to publish charts on tag push, not on push to `main`!

2024-04-25 07:50 UTC, jgiannuzzi commented on .github/workflows/release.yml
> +  chart-release:
you'll need to add `environment: release` for this to work now that the secrets have been created in this environment.

2024-05-09 15:35 UTC, jgiannuzzi commented on .github/workflows/release.yml
> +  chart-release:
excellent point, done!

The new key fingerprint is `dU/0iLRxlQu5Apyx8y16eVPqhsClH2BMCQiMdEEcyBU=`.

2024-05-09 16:59 UTC, jgiannuzzi submitted a review, later dismissed

2024-05-09 16:59 UTC, jgiannuzzi commented on .github/workflows/release.yml
> +      APP_PRIVATE_KEY: ${{ secrets.GH_APP_PEM }}
```suggestion
      APP_PRIVATE_KEY: ${{ secrets.APP_PRIVATE_KEY }}
```

2024-05-10 13:09 UTC, jgiannuzzi approved these changes
Thank you so much for this contribution @ljubon!

2024-05-10 13:10 UTC, merged